### 관리자 등록 - 실패 (성공 케이스는 admin password 보안 이슈로 테스트 후 지웠습니다.)
PUT http://localhost:8080/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraW1jaGFlbWluMDcwN0BnbWFpbC5jb20iLCJpZCI6MSwidXNlcm5hbWUiOiJjaGFlbWluIGtpbSIsIm5pY2tuYW1lIjoiY2hhZW1pbiBraW0iLCJpYXQiOjE3MjI5NTgwNDgsImV4cCI6MTcyMjk1ODY0OH0.sTtUy61e4g_PucFGnF_cMrovNGZ0824r23BM-2uOhRU

{
  "password": "wrongpassword"
}

### 방송 상세 정보 가져오기
GET http://localhost:8080/admin/broadcast/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGVhbWluNjMwNkBuYXZlci5jb20iLCJpZCI6MSwidXNlcm5hbWUiOiLquYDssYTrr7wiLCJuaWNrbmFtZSI6Iuq5gOyxhOuvvCIsImlhdCI6MTcyMzA4MTM1MywiZXhwIjoxNzIzMDgxOTUzfQ.rdsG25beo-1n6PrGm9s2N2Unp577wlBOwD7nZMWkehE

### 구매자 목록 가져오기
GET http://localhost:8080/admin/broadcast/1/consumer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGVhbWluNjMwNkBuYXZlci5jb20iLCJpZCI6MSwidXNlcm5hbWUiOiLquYDssYTrr7wiLCJuaWNrbmFtZSI6Iuq5gOyxhOuvvCIsImlhdCI6MTcyMzEwMTczNSwiZXhwIjoxNzIzMTAyMzM1fQ.uwJFIKbSx7ZOaHmOCjXkNjOc7YYcfZXLVjR_97ZHtyE

### 관리자 권한 체크 확인
GET http://localhost:8080/admin/broadcasts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGVhbWluNjMwNkBuYXZlci5jb20iLCJpZCI6MSwidXNlcm5hbWUiOiLquYDssYTrr7wiLCJuaWNrbmFtZSI6Iuq5gOyxhOuvvCIsImlhdCI6MTcyMzQzNDU1MCwiZXhwIjoxNzIzNDM1MTUwfQ.jZDznqaHXUjxYhXS0w5az3Hni7tvdKasFMxqtcaBtGw
