### 방송 생성
POST http://localhost:8080/broadcast
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraHU0MjM3QGdtYWlsLmNvbSIsIm5pY2tuYW1lIjoi7J6Q65GQ66eM65GQIiwiaWF0IjoxNzIxOTgyMDUyLCJleHAiOjE3MjE5ODI2NTJ9.0KyUz_g9tj0F8iUV7vv-gDayxBATyyoseerqN08R1wU

{
  "title": "맛있는 선산곱창 90% 할인",
  "code": "1234123412341234",
  "product_id": 1
}

### 방송 내역 조회
GET http://localhost:8080/user/broadcast
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraHU0MjM3QGdtYWlsLmNvbSIsIm5pY2tuYW1lIjoi7J6Q65GQ66eM65GQIiwiaWF0IjoxNzIxOTc4MzgyLCJleHAiOjE3MjE5Nzg5ODJ9.Uj30VvGZ1OL8Rcf_4ZjHJTHuiIpsmHqgYx5hSbQaG0o
d
### 방송 중단
PATCH http://localhost:8080/broadcast
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraHU0MjM3QGdtYWlsLmNvbSIsIm5pY2tuYW1lIjoi7J6Q65GQ66eM65GQIiwiaWF0IjoxNzIxOTgyMDUyLCJleHAiOjE3MjE5ODI2NTJ9.0KyUz_g9tj0F8iUV7vv-gDayxBATyyoseerqN08R1wU